---
title: "SDS 192 Mini-Project 2"
subtitle: "SDS 192"
author: 
- name: Kat Brady
  affiliation: Smith College
- name: Ellie Zdancewic
  affiliation: Smith College
date: "`r format(Sys.Date(), '%B %e, %Y')`"
editor: 
  mode: source
output: 
  html_document:
    fig_width: 7
    fig_height: 6
    fig_caption: true
    theme: lumen
    df_print: paged
    code_folding: show
---

```{r setup}
library(tidyverse)
library(fec20)
options(scipen = 10)
```

```{r helper-chunk}
# Look at help file
?contributions

# Note that the contributions data frame only contains the first 1000 rows:
contributions

# Download full contributions data from web and overwrite contributions using:
# read_all_*() function.
# You will need to install the usethis package for this line of code to work
contributions <- read_all_contributions()

# Now contributions has full 887,823 rows
contributions
```

```{r analysis-1}
#Kat's work in below chunks---------
```

```{r}
#making the data set smaller and filtering for relevant information
condensed_contributions<-contributions|>
  select(transaction_tp, entity_tp, name, transaction_amt,cand_id)

condensed_candidates<-candidates|>
  select(cand_id, cand_name, cand_pty_affiliation, cand_office)|>
  filter(cand_office=="P", cand_pty_affiliation%in%c("REP", "DEM"))
#joining the data with some data from candidates to add the candidates' names
contributions2<-condensed_contributions|>
  inner_join(condensed_candidates,
             by=c("cand_id"))
```

```{r}
#filtering for just Trump and Biden
contributions2<- contributions2|>
  filter(cand_id%in%c("P80001571","P80000722"))|>
  select(transaction_tp,entity_tp,name,transaction_amt,cand_id,cand_name)
```

```{r}
#Recoding the names of transactions to be more reader-friendly
contributions2$transaction_tp<-
  recode(contributions2$transaction_tp,
         "24E"="In Favor",
         "24K"="In Favor",
         "24A"="Against",
         "24C"="In Favor",
         "24N"="Against",
         "24F"="In Favor",
         "24Z"="In Favor")
```
```{r}
#This combines the multiple contributions made by one group so that the total amount contributed by one group is shown rather than every individual donation being shown differently
groupcontributions<- groupcontributions2|>
  group_by(transaction_tp, entity_tp, name, cand_name)|>
  summarize(total=sum(transaction_amt))
```
```{r}
#To see the total quantity contributed to and against Biden And Trump by organizations, this last summary move is completed
sumcontributions<- groupcontributions|>
  group_by(transaction_tp, cand_name)|>
  summarize(total=sum(total))
```
```{r}
sumcontributions|>
ggplot(aes(x=total, y=cand_name, fill=transaction_tp))+
  geom_col()+
  coord_flip()+
  labs(title="Total Contributed to Leading Candidates by Groups*",
       subtitle="*In this case, 'groups' refers to non-individuals, including
committees, candidates, candidate committees, PACs,
and organizations",
x="Total (In USD)",
y="Candidate",
fill="Transaction",
caption="Source:
https://www.fec.gov/campaign-finance-data/contributions-committees-candidates-file-description/")+
scale_fill_manual(values=c("#ab400c","#65995c"))
```




```{r analysis-2}
# Ellie's Work------------------------------------------------------------------------------------- 
```

```{r}
#checking if there are any IND values in our dataset 
contributions_condensed_ind <- condensed_contributions |>
  filter(entity_tp %in% c("IND")) 
glimpse(contributions_condensed_ind)

```

Question of interest: 
What are the economic demographics of individuals who donate to campaigns? Does one party receive more contributions from individuals greater than $10,000 than another? Does one party receive more contributions from individuals less than $1000 than another? 

```{r}
#Joining contributions with cand_id to match up Candidate names with Candidate IDs 
contributions3<-contributions|>
  inner_join(condensed_candidates,
             by=c("cand_id"))
```

```{r}
#creating a dataframe of only IND values regardless of amount contributed
contributions3_ind <- contributions3 |>
  filter(entity_tp %in% c("IND")) 
glimpse(contributions_condensed_ind)
```

```{r}
#filtering for contributions to Trump and Biden
contributions3_ind <- contributions3_ind |>
  filter(cand_name %in% c("BIDEN, JOSEPH R JR", "TRUMP, DONALD J.")) 
```

```{r}
#selecting only for relevant columns 
contributions3_ind<- contributions3_ind|>
  select(transaction_tp, name, city, state, transaction_amt,cand_name)
```

```{r}
#Recoding the names of transactions to be more reader-friendly
contributions3_ind$transaction_tp<-
  recode(contributions3_ind$transaction_tp,
         "24E"="In Favor",
         "24K"="In Favor",
         "24A"="Against")
```

```{r}
#doesn't work yet 
#replacing instances of double commas with a single comma 
contributions3_ind_without_commas |> 
  str_replace_all(",,",",")
```

```{r}
#combining donors of the same name into one observation 
contributions3_ind_grouped<- contributions3_ind|>
  group_by(name, cand_name) |>
  summarise(total_amt = sum(transaction_amt))
```














```

```{r analysis-3}
# Group member 3 work here!



















```

# Blog post

Compose your blog post here...



